controller_list:
  - name: /rt_traj_exe
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - waist_joint
      - head_pan_joint
      - head_tilt_joint

  - name: /ur_driver_left_arm_
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint

  - name: /ur_driver_right_arm_
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
